
# Settings for ros_control hardware interface
hardware_interface:
  loop_hz: 50 # hz
  joints:
    - left_front_wheel2base_link
    - left_rear_wheel2base_link
    - right_rear_wheel2base_link
    - right_front_wheel2base_link