<!--
    使用 xacro 优化 URDF 版的小车底盘实现：

    实现思路:
    1.将一些常量、变量封装为 xacro:property
      比如:PI 值、小车底盘半径、离地间距、车轮半径、宽度 ....
    2.使用 宏 封装驱动轮以及支撑轮实现，调用相关宏生成驱动轮与支撑轮

-->
<!-- 根标签，必须声明 xmlns:xacro -->
<robot name="mecanumbot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 封装变量、常量 -->
    <!-- PI 值设置精度需要高一些，否则后续车轮翻转量计算时，可能会出现肉眼不能察觉的车轮倾斜，从而导致模型抖动 -->
    <xacro:property name="PI" value="3.1415926"/>
    <!-- 宏:黑色设置 -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <!-- 底盘属性 -->
    <xacro:property name="base_footprint_radius" value="0.001" /> <!-- base_footprint 半径  -->
    <xacro:property name="base_link_length" value="0.56" /> <!-- base_link 长 -->
    <xacro:property name="base_link_width" value="0.36" /> <!-- base_link 宽 -->
    <xacro:property name="base_link_height" value="0.23" /> <!-- base_link 高 -->
    <xacro:property name="wheel_offset" value="0.087" /> <!-- 轮偏置距离  -->
    <xacro:property name="wheel_distance" value="0.44" /> <!-- 前后轮轴距  -->
    <xacro:property name="earth_space" value="0.14" /> <!-- 离地间距 -->
    <xacro:property name="base_link_m" value="5" /> <!-- 质量  -->

    <!-- 底盘 -->
    <link name="base_footprint">
      <visual>
        <geometry>
          <sphere radius="${base_footprint_radius}" />
        </geometry>
      </visual>
    </link>

    <link name="base_link">
      <visual>
        <geometry>
          <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="yellow">
          <color rgba="0.5 0.3 0.0 0.5" />
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:Box_inertial_matrix m="${base_link_m}" l="${base_link_length}" w="${base_link_width}" h="${base_link_height}" />

    </link>


    <joint name="base_link2base_footprint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 ${earth_space + base_link_height / 2 }" />
    </joint>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- 驱动轮 -->
    <!-- 驱动轮属性 -->
    <xacro:property name="wheel_radius" value="0.076" /><!-- 半径 -->
    <xacro:property name="wheel_length" value="0.046" /><!-- 宽度 -->
    <xacro:property name="wheel_m" value="0.25" /> <!-- 质量  -->

    <!-- 驱动轮宏实现 -->
    <xacro:macro name="add_wheels" params="name flag1 flag2">
      <link name="${name}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
          <material name="black" />
        </visual>
        <collision>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_radius}" h="${wheel_length}" />

      </link>

      <joint name="${name}_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="${name}_wheel" />
        <origin xyz="${flag2 * ( wheel_distance / 2)} ${flag1 * ((base_link_width - wheel_length) / 2) + flag1 * wheel_offset} ${-(earth_space + base_link_height / 2 - wheel_radius) }" />
        <axis xyz="0 1 0" />
      </joint>

        <!-- Transmission is important to link the joints and the controller -->
      <transmission name="${name}_wheel2base_link_trans">
          <type>transmission_interface/SimpleTransmission</type>
          <joint name="${name}_wheel2base_link">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          </joint>
          <actuator name="${name}_wheel2base_link_motor">
                <mechanicalReduction>1</mechanicalReduction>
          </actuator>
      </transmission>

      <gazebo reference="${name}_wheel">
        <material>Gazebo/Red</material>
      </gazebo>

    </xacro:macro>
    <xacro:add_wheels name="left_front" flag1="1" flag2="1"  />
    <xacro:add_wheels name="right_front" flag1="-1" flag2="1" />
    <xacro:add_wheels name="left_rear" flag1="1" flag2="-1" />
    <xacro:add_wheels name="right_rear" flag1="-1" flag2="-1" />

</robot>
